// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htrxgootmcitjbuwwgiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0cnhnb290bWNpdGpidXd3Z2l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTk3MzAsImV4cCI6MjA2MzkzNTczMH0.eSWlNTYbPtFsl6powfLQeXkDi26XdiXq78HEVCRErpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);