// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agakpbtckqvajcrjsbyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnYWtwYnRja3F2YWpjcmpzYnl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNDAwNDAsImV4cCI6MjA2NTkxNjA0MH0.Sb-btviT2lHTtgPyAxwlAQ5PAY5-_t8OeONyZ9Yttn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);